= Spring Data Neo4j Example Project

This project uses the Marvel comic data set to demonstrate using Spring Data and Neo4j together.
The following components are part of the project:

1. Neo4j database - https://dev.neo4j.com/sandbox[sandbox^], https://dev.neo4j.com/aura[Aura free tier^], or https://dev.neo4j.com/desktop[local instance].
2. Marvel comic data set loaded to Neo4j - Cypher statements in this repository.
3. Spring Boot application using Spring Data Neo4j (SDN) - https://spring.io/projects/spring-data-neo4j[Spring Data project^] for integration with Neo4j.

The application is a read-only interface to query and explore the data.
It is using the reactive capabilities of Spring Data Neo4j. For imperative functionality, please see the https://github.com/JMHReif/sdn-marvel-basic[related Github project^].

== Data set

"Data provided by Marvel. © 2014 Marvel"

Note that this project uses a subset (only characters and comic issues) of the full Marvel data set.
The trimmed down demo data set has been made available via a CSV or a JSON file.
Load queries for each are included in the load script.

To access and load the full Marvel data set, you will need an API key.
More details on this and loading the full data can be found on https://github.com/JMHReif/graph-demo-datasets/tree/main/marvel-comics[another Github repository^].

== Example REST API calls

* Characters
[source,bash]
----
http://localhost:8080/characters

http://localhost:8080/characters/Captain%20America
----

* ComicIssues
[source,bash]
----
http://localhost:8080/comics

http://localhost:8080/comics/Captain%20America%20(1968)%20%23132
----

[NOTE]
--
Methods with a `Flux` as the return type will continue outputting results until it returns every object found.
To stop the request before it finishes displaying the output, click the `X` in the browser or use `Cntrl + C` at the command line.
--